### PR TITLE
upgrade to spring boot 3

### PR DESCRIPTION
**Pull request by joanjanku2000**

### CODE REVIEW

**Review by robertotru — APPROVED** [review]
Thanks a lot for the PR. Looks good.

**Comment by robertotru** [comment]
@joanjanku2000  It's a pity, I think I have to publish the artifact under a new groupid.
It will take some days

**Comment by joanjanku2000** [comment]
Okay , no problem we can wait. Tha nk you again. Please let me know when you release it

**Comment by robertotru** [comment]
@joanjanku2000  I'm trying to release version 1.0.0 for JDK17.
It seems `mvn clean install` doesn't work. Was it working for you?
It fails to compile the module for freemarker with a message `package it.ozimov.springboot.mail.service does not exist` and I'm currently trying to understanding why.

I have to admit that I'm not using Maven since some years and I may have missed some important update in order to use it with latest JDKs

**Comment by joanjanku2000** [comment]
I am compiling it from IntellIJ's maven and it builds sucessfully. (both libraries)
image
image

**Comment by robertotru** [comment]
@joanjanku2000 I think you shown me  a build of core
When you release, you build the whole project.
I have this error locally
image
And the same with the release action configured in GitHub.
image

**Comment by joanjanku2000** [comment]
@robertotru Even the whole project runs successfully for me. That's strange. My maven version is 3.8.1. Can you try with this maven version if we don't have the same ?
image

image

**Comment by robertotru** [comment]
But even if it works on IJ, it doesn't work on GitHub.
I see that you didn't pull from master, since I see version 0.6.5-SNAPSHOT.
Can you pull and try again?

**Comment by robertotru** [comment]
Oooh! Found it @joanjanku2000 .
It was this line in the pom that I added today
```xml
        <finalName>${project.groupId}:${project.artifactId}</finalName>
```

**Comment by joanjanku2000** [comment]
Awesomeee. What one single character can do in our line of work 😂 Thank you for taking the time. 😁

**Comment by robertotru** [comment]
I had to open a ticket. https://issues.sonatype.org/browse/OSSRH-97186

**Comment by joanjanku2000** [comment]
@robertotru Thank you. I hope they resolve it soon.

**Comment by robertotru** [comment]
@joanjanku2000 I see a package on maven with version 1.0.0

Can you double check that it works?

**Pull request merged**
